# Generated by Django 3.1.7 on 2021-03-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='response',
        ),
    ]
